services:
    millervein.calendar.form.handler.hours:
        class: MillerVein\Bundle\CalendarBundle\Form\Handler\HoursFormHandler
        arguments:
            - "@millervein.calendar.hours_manager"