services:
    millervein.calendar.repository.appointment_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - MillerVein\Bundle\CalendarBundle\Entity\Appointment\Appointment
            
    millervein.calendar.repository.hours_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - MillerVein\Bundle\CalendarBundle\Entity\Hours
            
    millervein.calendar.calendar_builder:
        class: MillerVein\Bundle\CalendarBundle\Model\CalendarBuilder
        arguments: 
            - "@millervein.calendar.repository.appointment_repository"
#        alias: calendar_builder

    millervein.calendar.unique_appointment_time_validator:
        class: MillerVein\Bundle\CalendarBundle\Validator\UniqueAppointmentTimeValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: validator.constraint_validator
                alias: unique_appointment_time
    millervein.calendar.appointment_time_hours_validator:
        class: MillerVein\Bundle\CalendarBundle\Validator\HoursAppointmentTimeValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: validator.constraint_validator
                alias: valid_hours_appointment_time
    millervein.calendar.category_column_validator:
        class: MillerVein\Bundle\CalendarBundle\Validator\CategoryColumnValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: validator.constraint_validator
                alias: category_column
    millervein.calendar.no_past_appointments_validator:
        class: MillerVein\Bundle\CalendarBundle\Validator\NoPastAppointmentsValidator
        tags:
            -
                name: validator.constraint_validator
                alias: no_past_appointments
                
    millervein.calendar.hours_manager:
        class: MillerVein\Bundle\CalendarBundle\DomainManager\HoursManager
        arguments:
            - "@doctrine.orm.entity_manager"
    hours_manager:
        alias: millervein.calendar.hours_manager