miller_vein_patient_tracker:
    resource: "@EMRPatientTrackerBundle/Controller/"
    type:     annotation
    prefix:   /patient_tracker

miller_vein_calendar:
    resource: "@EMRCalendarBundle/Controller/"
    type:     annotation
    prefix:   /
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"