miller_vein_calendar:
    resource: "@MillerVeinCalendarBundle/Controller/"
    type:     annotation
    prefix:   /
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"