services:
    # Repos #
    emr.calendar.repository.appointment_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - EMR\Bundle\CalendarBundle\Entity\Appointment\Appointment
    appointment_repository:
        alias: emr.calendar.repository.appointment_repository
    emr.calendar.repository.patient_appointment_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - EMR\Bundle\CalendarBundle\Entity\Appointment\PatientAppointment
    patient_appointment_repository:
        alias: emr.calendar.repository.patient_appointment_repository
    emr.calendar.repository.hours_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - EMR\Bundle\CalendarBundle\Entity\Hours
    emr.calendar.repository.utilization_metric_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - EMR\Bundle\CalendarBundle\Entity\UtilizationMetric
    emr.calendar.repository.utilization_goal_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - EMR\Bundle\CalendarBundle\Entity\UtilizationGoal
    emr.calendar.repository.goal_reward_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - EMR\Bundle\CalendarBundle\Entity\GoalReward
            
    # Validators #
    emr.calendar.unique_appointment_time_validator:
        class: EMR\Bundle\CalendarBundle\Validator\UniqueAppointmentTimeValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: validator.constraint_validator
                alias: unique_appointment_time
    emr.calendar.appointment_time_hours_validator:
        class: EMR\Bundle\CalendarBundle\Validator\HoursAppointmentTimeValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: validator.constraint_validator
                alias: valid_hours_appointment_time
    emr.calendar.category_column_validator:
        class: EMR\Bundle\CalendarBundle\Validator\CategoryColumnValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: validator.constraint_validator
                alias: category_column
    emr.calendar.no_past_appointments_validator:
        class: EMR\Bundle\CalendarBundle\Validator\NoPastAppointmentsValidator
        tags:
            -
                name: validator.constraint_validator
                alias: no_past_appointments
            
    # Managers #
    emr.calendar.hours_manager:
        class: EMR\Bundle\CalendarBundle\DomainManager\HoursManager
        arguments:
            - "@doctrine.orm.entity_manager"
    hours_manager:
        alias: emr.calendar.hours_manager
        
    # Misc #    
    emr.calendar.calendar_builder:
        class: EMR\Bundle\CalendarBundle\Model\CalendarBuilder
        arguments: 
            - "@emr.calendar.repository.appointment_repository"
    emr.calendar.appointment_mover:
        class: EMR\Bundle\CalendarBundle\Model\AppointmentMover
        arguments: 
            - "@doctrine.orm.entity_manager"
    emr.calendar.calendar_request:
        class: EMR\Bundle\CalendarBundle\Model\CalendarRequest
        arguments:
            - "@emr.legacy.repository.site"
            
    # Calculators #
    emr.calendar.used_time_calculator:
        class: EMR\Bundle\CalendarBundle\Model\Reports\UsedTimeCalculator
    emr.calendar.open_time_calculator:
        class: EMR\Bundle\CalendarBundle\Model\Reports\OpenTimeCalculator
    emr.calendar.utilization_calculator:
        class: EMR\Bundle\CalendarBundle\Model\Reports\UtilizationCalculator
        arguments:
            - "@emr.calendar.used_time_calculator"
            - "@emr.calendar.open_time_calculator"
            
            
    emr.calendar.utilization.report.goals:
        class: EMR\Bundle\CalendarBundle\Model\Reports\UtilizationGoalReport
        arguments:
            - "@emr.calendar.repository.utilization_metric_repository"
            - "@emr.calendar.repository.utilization_goal_repository"
            - "@emr.calendar.repository.goal_reward_repository"
            - "@emr.calendar.utilization_calculator"
        