services:
    millervein.patient_tracker.form.type.site:
        class: MillerVein\PatientTrackerBundle\Form\Type\SiteType
        tags:
            - { name: form.type, alias: site }
    millervein.patient_tracker.form.type.room:
        class: MillerVein\PatientTrackerBundle\Form\Type\RoomType
        tags:
            - { name: form.type, alias: room }
    millervein.patient_tracker.listener.appointment.onflush:
        class: MillerVein\PatientTrackerBundle\EventListener\AppointmentEventListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }