services:
    millervein.calendar.form.type.recurrence_rule:
        class: MillerVein\CalendarBundle\Form\Type\RecurrenceRuleType
        tags:
            - { name: form.type, alias: recurrence_rule }
    millervein.calendar.form.type.hours:
        class: MillerVein\CalendarBundle\Form\Type\HoursType
        tags:
            - { name: form.type, alias: hours }
    millervein.calendar.form.type.column:
        class: MillerVein\CalendarBundle\Form\Type\ColumnType
        tags:
            - { name: form.type, alias: column }
    millervein.calendar.form.type.site:
        class: MillerVein\CalendarBundle\Form\Type\SiteType
        tags:
            - { name: form.type, alias: site }
    millervein.calendar.form.type.calendar:
        class: MillerVein\CalendarBundle\Form\Type\CalendarType
        tags:
            - { name: form.type, alias: calendar }
            
#-- Appointment -- #
    millervein.calendar.form.type.appointment.patient:
        class: MillerVein\CalendarBundle\Form\Type\Appointment\PatientType
        tags:
            - { name: form.type, alias: appointment_patient }
    millervein.calendar.form.type.appointment.provider:
        class: MillerVein\CalendarBundle\Form\Type\Appointment\ProviderType
        tags:
            - { name: form.type, alias: appointment_provider }
#-- End Appointment -- #
            
#-- Category -- #
    millervein.calendar.form.type.category.patient:
        class: MillerVein\CalendarBundle\Form\Type\Category\PatientType
        tags:
            - { name: form.type, alias: category_patient }
    millervein.calendar.form.type.category.provider:
        class: MillerVein\CalendarBundle\Form\Type\Category\ProviderType
        tags:
            - { name: form.type, alias: category_provider }
#-- End Category -- #
            
#   Form Fields
    millervein.calendar.form.type.fields.color:
        class: MillerVein\CalendarBundle\Form\Type\Fields\ColorType
        tags:
            - { name: form.type, alias: color }