services:
    millervein.calendar.form.type.recurrence_rule:
        class: MillerVein\CalendarBundle\Form\Type\RecurrenceRuleType
        tags:
            - { name: form.type, alias: recurrence_rule }
    millervein.calendar.form.type.hours:
        class: MillerVein\CalendarBundle\Form\Type\HoursType
        tags:
            - { name: form.type, alias: hours }
    millervein.calendar.form.type.column:
        class: MillerVein\CalendarBundle\Form\Type\ColumnType
        tags:
            - { name: form.type, alias: column }
    millervein.calendar.form.type.column_tag:
        class: MillerVein\CalendarBundle\Form\Type\ColumnTagType
        tags:
            - { name: form.type, alias: column_tag }
    millervein.calendar.form.type.site:
        class: MillerVein\CalendarBundle\Form\Type\SiteType
        tags:
            - { name: form.type, alias: site }
    millervein.calendar.form.type.calendar:
        class: MillerVein\CalendarBundle\Form\Type\CalendarType
        tags:
            - { name: form.type, alias: calendar }
    millervein.calendar.form.type.patient_selector:
        class: MillerVein\CalendarBundle\Form\Type\PatientSelectorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: patient_selector }
    millervein.calendar.form.type.appointment_status:
        class: MillerVein\CalendarBundle\Form\Type\AppointmentStatusType
        tags:
            - { name: form.type, alias: appointment_status }
            
#-- Appointment -- #
    millervein.calendar.form.type.appointment.patient:
        class: MillerVein\CalendarBundle\Form\Type\Appointment\PatientAppointmentType
        tags:
            - { name: form.type, alias: appointment_patient }
    millervein.calendar.form.type.appointment.provider:
        class: MillerVein\CalendarBundle\Form\Type\Appointment\ProviderAppointmentType
        tags:
            - { name: form.type, alias: appointment_provider }
#-- End Appointment -- #
            
#-- Category -- #
    millervein.calendar.form.type.category.patient:
        class: MillerVein\CalendarBundle\Form\Type\Category\PatientCategoryType
        tags:
            - { name: form.type, alias: category_patient }
    millervein.calendar.form.type.category.provider:
        class: MillerVein\CalendarBundle\Form\Type\Category\ProviderCategoryType
        tags:
            - { name: form.type, alias: category_provider }
#-- End Category -- #
            
#   Form Fields
    millervein.calendar.form.type.fields.color:
        class: MillerVein\CalendarBundle\Form\Type\Fields\ColorType
        tags:
            - { name: form.type, alias: color }
            
            
    millervein.calendar.repository.appointment_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - MillerVein\CalendarBundle\Entity\Appointment\Appointment
#    millervein.calendar.calendar:
#        class: MillerVein\CalendarBundle\Model\Calendar
#        arguments: ["@millervein.calendar.repository.appointment_repository"]

    millervein.calendar.unique_appointment_time_validator:
        class: MillerVein\CalendarBundle\Validator\UniqueAppointmentTimeValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: validator.constraint_validator
                alias: unique_appointment_time