services:
    millervein.calendar.form.type.recurrence_rule:
        class: MillerVein\CalendarBundle\Form\Type\RecurrenceRuleType
        tags:
            - { name: form.type, alias: recurrence_rule }
    millervein.calendar.form.type.hours:
        class: MillerVein\CalendarBundle\Form\Type\HoursType
        tags:
            - { name: form.type, alias: hours }
    millervein.calendar.form.type.column:
        class: MillerVein\CalendarBundle\Form\Type\ColumnType
        tags:
            - { name: form.type, alias: column }
    millervein.calendar.form.type.site:
        class: MillerVein\CalendarBundle\Form\Type\SiteType
        tags:
            - { name: form.type, alias: site }